# Importando Base de Dados Itens Kawasaki

## 1- BASE KAWASAKI

### 1.1 - Instalar Biblioteca cx_Oracle

In [22]:
pip install cx_Oracle

Requirement already satisfied: cx_Oracle in c:\users\pedro\anaconda3\lib\site-packages (8.3.0)
Note: you may need to restart the kernel to use updated packages.

### 1.2 - Importar Biblioteca cx_Oracle

In [23]:
import cx_Oracle

try:
    cx_Oracle.init_oracle_client(lib_dir=r"C:\oracle\instantclient_19_16") # instantclient_11_2

except:
    print('Já está rodando')

Já está rodando

### 1.3 - Criando Conexão com Banco Oracle

In [24]:
dsn_tns    = cx_Oracle.makedsn('***.**.**.***', '1521', service_name='*****')
connection = cx_Oracle.connect(user=r'*****', password='****', dsn=dsn_tns)

### 1.4 - Consulta Banco de Dados

In [25]:
cursor1 = connection.cursor()
cursor1.execute("""select  msi.organization_id
        , msi.segment1 
        , TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x') as desc_MASTER
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_B01
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 149 ) as desc_B01
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_B02
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 152 ) as desc_B02
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_B03
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 150 ) as desc_B03
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_B04
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 151 ) as desc_B04      
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_B07
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 148 ) as desc_B07             
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_B08
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 153 ) as desc_B08
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_B09
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 154 ) as desc_B09
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_A06
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 157 ) as desc_A06             
        , (select TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') as desc_A05
           from apps.mtl_system_items_b item 
           where item.inventory_item_id = msi.inventory_item_id
             and TRANSLATE(item.description, 'x'||CHR(10)||CHR(13), 'x') <> TRANSLATE(msi.description, 'x'||CHR(10)||CHR(13), 'x')   
             and item.organization_id = 158 ) as desc_A05
        --- COMPARA NCM nas MULTIPLAS ORGANIZAÇÕES     
        , mic.segment1 as NCM_ITEM_MASTER
        ---
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 149 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_B01 
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 152 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_B02 
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 150 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_B03 
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 151 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_B04 
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 148 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_B07 
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 153 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_B08 
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 154 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_B09 
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 157 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_A06 
        , (select cat.segment1 as NCM_ORG  
             from apps.MTL_ITEM_CATEGORIES_V cat 
            where msi.inventory_item_id = cat.inventory_item_id
              and to_number(cat.organization_id) = 158 
              and cat.category_set_name = 'FISCAL_CLASSIFICATION' 
              and cat.segment1 <> mic.segment1 ) as NCM_A05               
        -- DESCRIÇÃO LONGA 
        , msitl.LONG_DESCRIPTION DESLONGA_MASTER
        -- 
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 149 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_B01
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 152 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_B02
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 150 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_B03
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 151 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_B04
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 148 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_B07
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 153 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_B08
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 154 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_B09
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 157 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_A06
        , (select tl.LONG_DESCRIPTION as DESC_L  
             from apps.MTL_SYSTEM_ITEMS_TL tl 
            where msi.inventory_item_id = tl.inventory_item_id
              and tl.organization_id = 158 
              and tl.language = 'PTB'
              and tl.LONG_DESCRIPTION <> msitl.LONG_DESCRIPTION ) as DESLONGA_A05
        , msi.CREATION_DATE
        , msi.LAST_UPDATE_DATE
        , msi.INVENTORY_ITEM_STATUS_CODE 
        , msi.PRIMARY_UOM_CODE
        , msi.PRIMARY_UNIT_OF_MEASURE
        , msi.GLOBAL_ATTRIBUTE3 Origem
        , msi.GLOBAL_ATTRIBUTE5 Sit_Trib_Federal
        , msi.GLOBAL_ATTRIBUTE6 Sit_Trib_Estatual
        , msi.GLOBAL_ATTRIBUTE9 Cod_Id_Sit_Tributaria
        , kp.jpn_tariff hs_code 
from  apps.mtl_system_items_b msi
    , apps.MTL_ITEM_CATEGORIES_V mic 
    , apps.MTL_SYSTEM_ITEMS_TL msitl
    , kmtb_parts@APPS2CIGAMPRD kp
where msi.inventory_item_id = mic.inventory_item_id
  and to_number(mic.organization_id) = msi.organization_id 
  and msi.organization_id =  msitl.organization_id
  and msi.inventory_item_id = msitl.inventory_item_id 
  and msitl.language = 'PTB'
  and mic.category_set_name = 'FISCAL_CLASSIFICATION'
  and msi.INVENTORY_ITEM_STATUS_CODE = 'Active'
  and msi.organization_id = 147 -- MASTER
  and kp.cd_material (+)= msi.segment1
""")
header  = cursor1.description
columns = [col[0] for col in header]
cursor1.rowfactory = lambda * args: dict(zip(columns,args))
data = cursor1.fetchall()

### 1.5 - Transformando Consulta em um DataFrame

In [26]:
import pandas as pd

In [27]:
dataset = pd.DataFrame(data)

In [28]:
dataset

,ORGANIZATION_ID,SEGMENT1,DESC_MASTER,DESC_B01,DESC_B02,DESC_B03,DESC_B04,DESC_B07,DESC_B08,DESC_B09,...,CREATION_DATE,LAST_UPDATE_DATE,INVENTORY_ITEM_STATUS_CODE,PRIMARY_UOM_CODE,PRIMARY_UNIT_OF_MEASURE,ORIGEM,SIT_TRIB_FEDERAL,SIT_TRIB_ESTATUAL,COD_ID_SIT_TRIBUTARIA,HS_CODE
0,147,92192-1779,"TUBO (MANGUEIRA), DE BORRACHA VULCANIZADA NAO ...",None,None,None,None,None,None,None,...,2019-12-21 12:36:01,2021-03-04 21:28:37,Active,PC,Peca,1,05,20,108700,4009110000
1,147,92192-1802,TUBO 3.2X7.4X55,None,None,None,None,None,None,None,...,2020-01-06 13:38:27,2020-01-06 13:38:27,Active,UN,Unidade,1,00,00,108700,4009110000
2,147,92192-1803,TUBO 3.5X7.5X70,None,None,None,None,None,None,None,...,2020-01-06 14:44:08,2020-01-06 14:44:08,Active,UN,Unidade,1,00,00,108700,4009110000
3,147,92192-1804,TUBO 3.5X7.5X115,None,None,None,None,None,None,None,...,2020-01-06 14:14:01,2020-01-06 14:14:01,Active,UN,Unidade,1,00,00,108700,4009110000
4,147,92192-1805,TUBO 3.2X7.4X175,None,None,None,None,None,None,None,...,2020-01-06 15:28:24,2020-01-06 15:28:24,Active,UN,Unidade,1,00,00,108700,4009110000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34150,147,300006,CENTRAL DE ALARME,None,None,CENTRAL DE ALARME NEW HARPIA 125 ENDEREÇOS CLB,None,CENTRAL DE ALARME NEW HARPIA 125 ENDEREÇOS CLB,CENTRAL DE ALARME NEW HARPIA 125 ENDEREÇOS CLB,CENTRAL DE ALARME NEW HARPIA 125 ENDEREÇOS CLB,...,2020-03-25 09:01:50,2022-09-24 22:26:09,Active,PC,Peca,0,02,90,2111300,None
34151,147,41080-0646 18U,"DISCO DE FREIO DA RODA DIANTEIRA, DE ACO, PINTADO",None,None,None,None,None,None,None,...,2019-12-21 16:50:07,2021-04-02 08:33:25,Active,PC,Peca,1,05,20,107600,None
34152,147,BC51(M)18R-BLK-0.5¿,TINTA,None,None,None,None,None,None,None,...,2022-02-09 10:01:22,2022-10-21 12:33:58,Active,UN,Unidade,1,05,00,2400100,None
34153,147,200213,"PARAFUSO SEXTAVADO FLANGEADO M8 1,25 X 20 RI 8...",None,None,None,None,None,None,None,...,2021-05-13 09:59:28,2021-05-14 08:24:59,Active,UN,Unidade,0,49,90,1005800,None
34154,147,58029-0014 290,"CARENAGEM FRONTAL, DE PLASTICO, PINTADA.",None,None,None,None,None,None,None,...,2020-07-06 10:59:19,2021-03-04 21:28:37,Active,PC,Peca,1,05,20,107600,None

### 1.6 - Exportando Base Kawasaki

In [29]:
dataset.to_excel('Base Dados Tratados/Base_Kawasaki.xlsx', index = False)

## 2- BASE NCM BRASIL

### 2.1 - Instalando Bibliotecas

In [30]:
pip install selenium

Requirement already satisfied: selenium in c:\users\pedro\anaconda3\lib\site-packages (4.7.2)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\pedro\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in c:\users\pedro\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\pedro\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\pedro\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: sortedcontainers in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: sniffio in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: async-generator>=1.9 in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.0.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: pycparser in c:\users\pedro\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\pedro\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\pedro\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\pedro\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

### 2.2 - Importando Bibliotecas

In [31]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time
from pathlib import Path
import shutil
import os
import pandas as pd

### 2.3 - Baixando Base

In [32]:
navegador = webdriver.Chrome()
navegador.get('https://portalunico.siscomex.gov.br/classif/#/nomenclatura/tabela?perfil=publico')
time.sleep(2)
navegador.find_element(By.TAG_NAME , 'body').send_keys(Keys.ESCAPE)
time.sleep(2)
navegador.find_element(By.ID, 'selectedFormato-selectized').send_keys(Keys.DOWN,Keys.DOWN,Keys.ENTER,Keys.TAB,Keys.ENTER)
time.sleep(2)
navegador.quit()

### 2.4 - Movendo Arquivos para pasta Base Dados

In [33]:
import fnmatch
for file in os.listdir('C:/Users/pedro/Downloads'):
    if fnmatch.fnmatch(file, 'Tabela_NCM_Desc_Concatenada*.xlsx'):
        
        file_correct = file
        file_source = "C:/Users/pedro/Downloads"
        file_destination = 'C:/Users/pedro/PROJETO NCM PYTHON/Base Dados/'

        get_files = os.listdir(file_source)
        
        try:
            if os.path.join(file_destination,file_correct):
                os.remove(file_destination+'/'+file_correct)
        except:
            for file1 in Path(file_source).glob(file_correct):
                shutil.move(os.path.join(file_source,file_correct),file_destination)
        else:
            for file1 in Path(file_source).glob(file_correct):
                shutil.move(os.path.join(file_source,file_correct),file_destination)

### 2.5 - Importando  Base NCM Brasil

In [34]:
import warnings

with warnings.catch_warnings(record = True):
    warnings.simplefilter("always")
    df_ncm_brasil = pd.read_excel(f'Base Dados/{file_correct}',engine="openpyxl", header=[3])
df_ncm_brasil

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Código,Descrição,Descrição Concatenada,Data Início,Data Fim,Ato Legal,Número,Ano
1,01,Animais vivos.,01: Animais vivos.,01/04/2022,31/12/9999,Res Camex,000272,2021
2,01.01,"Cavalos, asininos e muares, vivos.","01: Animais vivos. \n01.01: Cavalos, asininos ...",01/04/2022,31/12/9999,Res Camex,000272,2021
3,0101.2,- Cavalos:,"01: Animais vivos. \n01.01: Cavalos, asininos ...",01/04/2022,31/12/9999,Res Camex,000272,2021
4,0101.21.00,-- Reprodutores de raça pura,"01: Animais vivos. \n01.01: Cavalos, asininos ...",01/04/2022,31/12/9999,Res Camex,000272,2021
...,...,...,...,...,...,...,...,...
15059,9705.31.00,-- Com mais de 100 anos,"97: Objetos de arte, de coleção e antiguidades...",01/04/2022,31/12/9999,Res Camex,000272,2021
15060,9705.39.00,-- Outras,"97: Objetos de arte, de coleção e antiguidades...",01/04/2022,31/12/9999,Res Camex,000272,2021
15061,97.06,Antiguidades com mais de 100 anos.,"97: Objetos de arte, de coleção e antiguidades...",01/04/2022,31/12/9999,Res Camex,000272,2021
15062,9706.10.00,- Com mais de 250 anos,"97: Objetos de arte, de coleção e antiguidades...",01/04/2022,31/12/9999,Res Camex,000272,2021
15063,9706.90.00,- Outras,"97: Objetos de arte, de coleção e antiguidades...",01/04/2022,31/12/9999,Res Camex,000272,2021

### 2.6 - Tratando Base NCM Brasil

In [35]:
df_ncm_brasil.columns = df_ncm_brasil.iloc[0] 

df_ncm_brasil = df_ncm_brasil[1:]

df_ncm_brasil.head()

,Código,Descrição,Descrição Concatenada,Data Início,Data Fim,Ato Legal,Número,Ano
1,01,Animais vivos.,01: Animais vivos.,01/04/2022,31/12/9999,Res Camex,000272,2021
2,01.01,"Cavalos, asininos e muares, vivos.","01: Animais vivos. \n01.01: Cavalos, asininos ...",01/04/2022,31/12/9999,Res Camex,000272,2021
3,0101.2,- Cavalos:,"01: Animais vivos. \n01.01: Cavalos, asininos ...",01/04/2022,31/12/9999,Res Camex,000272,2021
4,0101.21.00,-- Reprodutores de raça pura,"01: Animais vivos. \n01.01: Cavalos, asininos ...",01/04/2022,31/12/9999,Res Camex,000272,2021
5,0101.29.00,-- Outros,"01: Animais vivos. \n01.01: Cavalos, asininos ...",01/04/2022,31/12/9999,Res Camex,000272,2021

### 2.7 - Exportando Base NCM Brasil

In [36]:
df_ncm_brasil.to_excel('Base Dados Tratados/Ncm_Brasil.xlsx', index = False)

## 3- BASE HS CODE

### 3.1 - Instalando Bibliotecas

In [37]:
pip install selenium

Requirement already satisfied: selenium in c:\users\pedro\anaconda3\lib\site-packages (4.7.2)
Requirement already satisfied: trio~=0.17 in c:\users\pedro\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\pedro\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\pedro\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\pedro\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: attrs>=19.2.0 in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: outcome in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: async-generator>=1.9 in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sniffio in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\pedro\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.0.0)
Requirement already satisfied: pycparser in c:\users\pedro\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\pedro\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\pedro\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\pedro\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

### 3.2 - Importando Biblioteca

In [38]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time
from pathlib import Path
import shutil
import os
import fnmatch
import pandas as pd

### 3.3 Baixando Base

In [39]:
navegador = webdriver.Chrome()
navegador.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjy7bWd7ur8AhXERLgEHQvbB60QFnoECAwQAQ&url=https%3A%2F%2Fwww.oecd.org%2Fsti%2Find%2FConversionKeyBTDIxE4PUB.xlsx&usg=AOvVaw27jKRnQ5rX6DWoqpisXykL')

correct_file2 = ''

while correct_file2 == '':
    for file in os.listdir('C:/Users/pedro/Downloads'):
        if fnmatch.fnmatch(file, 'ConversionKey*.xlsx'):
            correct_file2 = file
            navegador.quit()

#file_path = f'C:/Users/pedro/Downloads/{correct_file3}'

#while not os.path.exists(file_path):
#    time.sleep(1)
#    if os.path.isfile(file_path):
#        navegador.quit()

### 3.4 - Movendo Arquivos para pasta Base Dados

In [40]:
for file in os.listdir('C:/Users/pedro/Downloads'):
    if fnmatch.fnmatch(file, 'ConversionKey*.xlsx'):
        
        file_correct3 = file
        file_source = "C:/Users/pedro/Downloads"
        file_destination = 'C:/Users/pedro/PROJETO NCM PYTHON/Base Dados'

        get_files = os.listdir(file_source)
        
        try:
            if os.path.join(file_destination,file_correct3):
                os.remove(file_destination+'/'+file_correct3)
        except:
            for file1 in Path(file_source).glob(file_correct3):
                shutil.move(os.path.join(file_source,file_correct3),file_destination)
        else:
            for file1 in Path(file_source).glob(file_correct3):
                shutil.move(os.path.join(file_source,file_correct3),file_destination)

### 3.5 Importando Base HS Code

In [41]:
import warnings

with warnings.catch_warnings(record = True):
    warnings.simplefilter("always")
    df_hs_code = pd.read_excel(f'Base Dados/{file_correct3}',sheet_name='FromHSToISICToEC', engine="openpyxl")
df_hs_code

,HS,HS-6digit,HS-4digit,HS-2digit,Label,Desci3,Desci4,BEC,EUC,Note
0,0,010111,0101,01,"Horses, live pure-bred breeding",C01,D01,41,CAP,NaN
1,0,010119,0101,01,"Horses, live except pure-bred breeding",C01,D01,111,INT,NaN
2,0,010120,0101,01,"Asses, mules and hinnies, live",C01,D01,111,INT,NaN
3,0,010210,0102,01,"Bovine animals, live pure-bred breeding",C01,D01,41,CAP,NaN
4,0,010290,0102,01,"Bovine animals, live, except pure-bred breeding",C01,D01,111,INT,NaN
...,...,...,...,...,...,...,...,...,...,...
27223,4,99EU88,99EU,99,COMPONENTS OF COMPLETE INDUSTRIAL PLANTS NOT I...,Unallocated,Unallocated,0,XMISC,NaN
27224,4,99EU89,99EU,99,COMPONENTS OF COMPLETE INDUSTRIAL PLANTS NOT I...,Unallocated,Unallocated,0,XMISC,NaN
27225,4,99EU90,99EU,99,"RETURNED GOODS, NOT ELSEWHERE CLASSIFIED",Unallocated,Unallocated,0,XMISC,NaN
27226,4,99EU99,99EU,99,GOODS NOT ELSEWHERE CLASSIFIED,Unallocated,Unallocated,0,XMISC,NaN
27227,4,ADJSPR,ADJS,AD,ADJUSTMENT ALL CHAPTERS,Adjustment,Adjustment,0,XMISC,NaN

###  3.6 - Exportando Base HS Code

In [42]:
df_hs_code.to_excel('Base Dados Tratados/HS_CODE_Japan.xlsx', index = False)